services:
  api:
    image: api:local
    pull_policy: build
    build: ./api
    develop:
      watch:
        - action: rebuild
          path: ./api
          ignore: 
            - "sqlc/"
            - "sqlite/"
            - "*.yaml"
            - "*.sql"
    command: /api
    volumes:
      - "${LOCAL_WORKSPACE_FOLDER:-.}/api/sqlite/actual/fs.db:/db/fs.db"
      - "${LOCAL_WORKSPACE_FOLDER:-.}/sample directory:/mounts/sample directory"
      - "${LOCAL_WORKSPACE_FOLDER:-.}/sample directory:/mounts/sample directory2"
      - "${LOCAL_WORKSPACE_FOLDER:-.}/sample directory:/mounts/sample directory3"

  ui:
    image: ui:local
    pull_policy: build
    build:
      context: ./ui
      target: dev
    develop:
      watch:
        - action: sync
          path: ./ui
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./ui/package.json
        - action: rebuild
          path: ./ui/package-lock.json

  proxy: 
    image: docker.io/nginx:latest
    pull_policy: missing
    ports:
      - "80:80"
    volumes:
      - "${LOCAL_WORKSPACE_FOLDER:-.}/.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - ui
      - api

