services:
  api:
    build: ./api
    pull_policy: build
    develop:
      watch:
        - action: rebuild
          path: ./api
    image: api:local
    command: /api
    ports:
      - "80:80"
    volumes:
      - "${LOCAL_WORKSPACE_FOLDER:-.}/sample directory:/mounts/sample directory"

  web:
    build:
      context: ./web
      target: dev
    pull_policy: build
    develop:
      watch:
        - action: sync
          path: ./web
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./web/package.json
        - action: rebuild
          path: ./web/package-lock.json
    image: web:local
    ports:
      - "3000:3000"
