services:
  api:
    build: ./api
    pull_policy: build
    develop:
      watch:
        - action: rebuild
          path: ./api
    image: api:local
    command: /api
    ports:
      - "80:80"
    volumes:
      - "${LOCAL_WORKSPACE_FOLDER:-.}/sample directory:/mounts/sample directory"

  ui:
    build:
      context: ./ui
      target: dev
    pull_policy: build
    develop:
      watch:
        - action: sync
          path: ./ui
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./ui/package.json
        - action: rebuild
          path: ./ui/package-lock.json
    image: ui:local
    ports:
      - "3000:3000"
