// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
)

type Path struct {
	ID          int64
	Path        string
	ParentID    sql.NullInt64
	Information json.RawMessage
}
