// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
)

type Path struct {
	ID          int64           `json:"id"`
	Path        string          `json:"path"`
	ParentID    sql.NullInt64   `json:"parent_id"`
	Information json.RawMessage `json:"information"`
}
