// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	InsertPath(ctx context.Context, arg InsertPathParams) error
	ListPaths(ctx context.Context) ([]Path, error)
}

var _ Querier = (*Queries)(nil)
