// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"encoding/json"
)

const insertPath = `-- name: InsertPath :exec
;

INSERT INTO paths (path, information)
VALUES(?, ?)
`

type InsertPathParams struct {
	Path        string          `json:"path"`
	Information json.RawMessage `json:"information"`
}

func (q *Queries) InsertPath(ctx context.Context, arg InsertPathParams) error {
	_, err := q.db.ExecContext(ctx, insertPath, arg.Path, arg.Information)
	return err
}

const listPaths = `-- name: ListPaths :many
SELECT id, path, parent_id, information
FROM paths
`

func (q *Queries) ListPaths(ctx context.Context) ([]Path, error) {
	rows, err := q.db.QueryContext(ctx, listPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Path
	for rows.Next() {
		var i Path
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.ParentID,
			&i.Information,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
